language: java
script: mvn clean verify
jdk: oraclejdk8

services:
- postgresql

addons:
postgresql: "9.4"

deploy:
  app: ci-spring-boot

before_script:
- psql -c 'create database hello;' -U postgres
