language: java
script: mvn clean verify
jdk: oraclejdk8

services:
- postgresql

addons:
postgresql: "9.4"

postgres:
  adapter: postgresql
  database: hello
  username: postgres

before_script:
- "psql -c 'create database hello;' -U postgres"
- "rake db:migrate"
