defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: unicode
  adapter: postgresql
  host: localhost

development:
  adapter: postgresql
  encoding: utf8
  database: hello
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: hello
  pool: 5
  username: postgres